# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Journal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Journal
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'BSImagePicker', '~> 2.4'
  pod 'GooglePlaces'
  pod 'RxRealm'
  pod 'KMPlaceholderTextView'
  pod 'IQKeyboardManagerSwift'
  pod 'NYTPhotoViewer'
  pod 'Agrume'
  pod 'FLEX'
  target 'JournalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JournalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
